### ISSUE TITLE
ext-json のバージョンについて

### ISSUE THREAD

**Issue by Pon57** [ryo88c/BEAR.Authority#2]
https://github.com/ryo88c/BEAR.Authority/blob/49bb357671327ce65ebc015e20d83bfed76b3ab9/composer.json#L17
composer.json 上では ^1.5 が指定されています。
PHP の json のバージョンは 7.4 から PHP のバージョンと同じものが使われるらしく、PHP 7.4 から json extention のバージョンが条件から外れてしまうため、使えなくなっています
https://github.com/php/php-src/pull/4459

この ext-json のバージョンを絞っている or 上げてない理由はありますか？（無ければ PHP 7.4 以上でも使えるようにしたいです）

https://github.com/ryo88c/BEAR.Authority/blob/421a7617332973231c8c8e37e495cdbf438ea012/src/Audience.php#L12
ちなみに json extention が使われていそうなのはここだけでした

**Comment by ryo88c** [comment]
@Pon57 特にバージョンを限定している理由はないので、バージョンを指定せず使えるよう調整します。

**Comment by ryo88c** [comment]
@Pon57 こちら対応しましたのでイシューは閉じまーす。ご指摘ありがとうございました。

**Comment by Pon57** [comment]
@ryo88c ご対応ありがとうございました！
